### ISSUE TITLE
lo1.hashbang.sh deploy checklist

### ISSUE THREAD

**Issue by infrastation** [hashbang/shell-server#101]
This issue tracks the work done to get the new shell server 100% ready and in the pool.

- [ ] Install hardware with Debian 9.8.0 and configure it with Ansible.
- [x] Add A record (hashbang/admin-tools#152).
- [x] Add AAAA record (hashbang/admin-tools#153).
- [x] Fix Postfix configuration (done manually on the server, the bugfix is #93).
- [ ] Configure mail.hashbang.sh to accept mail from lo1.hashbang.sh.
- [x] Make `man hashbang` work (hashbang/shell-server#95 and #98).
- [ ] Install `hashbangctl` (#94).
- [x] Decide if everything remains on a single root filesystem or separate mount points like /home are required, and allocate spare 830GB of free disk space.
- [ ] Fix dotfiles such that weechat nick autocompletion puts `: ` after the nick, not just `:`.
- [ ] List the new server on https://hashbang.sh/server/stats and generally announce it as available.

**Comment by infrastation** [comment]
Given lack of specific input, I have allocated all free extents to the root filesystem LV, as that does not require a reboot. Feel free to reallocate later if necessary.

**Comment by infrastation** [comment]
The last item no longer stands as the server had to be shut down (the disks have been wiped). It is up to you whether to leave this issue open.

**Comment by RyanSquared** [comment]
I'm going to use this issue as a reverse checklist for rolling back some changes such as DNS records.

**Comment by infrastation** [comment]
It has been a while.
